Feature/firedoc google docs api control
searchspring/nebo pull request #15
Opened 2020-10-23 17:48 UTC by wafer-bw

2020-10-26 14:37 UTC, wafer-bw commented
@codeallthethingz - In the spirit of not spending too much more time on this task I have skipped the remaining comment in your review of the old [PR](https://github.com/searchspring/nebo/pull/13) about which env vars are missing because I already also added the env library and the dao logic, so it should narrow it down to 2-3 vars they need to make sure are working while keeping the ability to test various chunks of nebo without having creds for it all. If you'd still like me to add logic to indicate which exact env var is missing lmk.

2020-10-26 15:44 UTC, codeallthethingz requested changes
Generally this PR has increased the code quality enormously.  🎉 

Some minor changes for readability.
One semantic regression that I don't think we should lose around the name of the non-set environment variable.

2020-10-26 15:44 UTC, codeallthethingz commented on api/index.go
>  	}
somewhere in here the error message needs to contain which environment variable was not set.  I don't think it does that.

2020-10-26 15:44 UTC, codeallthethingz commented on api/index.go
> +	if gapiDAO == nil && !containsEmptyString(gapiVars...) {
`gapiDAO == nil && !containsEmptyString` is difficult to parse for a human. 

Wherever you see a compound if statement it's a good idea to extract it to a descriptive method name.

`if shouldCreateDAO(params) {`

2020-10-26 15:44 UTC, codeallthethingz commented on gapi/gapi.go
> +	now := time.Now().Format(time.RFC3339)
you may want to specify the timezone.

2020-10-26 15:44 UTC, codeallthethingz commented on gapi/gapi.go
> +	bulletPreset := "BULLET_DISC_CIRCLE_SQUARE"
Is this not a constant somewhere in the google API?

2020-10-26 19:53 UTC, wafer-bw commented on gapi/gapi.go
> +	bulletPreset := "BULLET_DISC_CIRCLE_SQUARE"
Looks like they just accept strings?
https://godoc.org/google.golang.org/api/docs/v1

2020-10-26 20:12 UTC, wafer-bw commented on gapi/gapi.go
> +	now := time.Now().Format(time.RFC3339)
This should use the local time of where it's deployed. If that becomes a problem I can figure something out.

2020-10-26 20:46 UTC, codeallthethingz requested changes
needs some refactoring.

2020-10-26 20:46 UTC, codeallthethingz commented on validator/validator.go
> +		if strings.Trim(v, " ") == "" {
`strings.TrimSpace`

2020-10-26 20:46 UTC, codeallthethingz commented on gapi/dao.go
> +	bulletPreset := "BULLET_DISC_CIRCLE_SQUARE"
is this a constant in a package somewhere?

2020-10-26 20:46 UTC, codeallthethingz commented on gapi/gapi.go
> +func jsonDecode(body io.ReadCloser) map[string]interface{} {
There's probably an existing object in the google golang api that you can unmarshal into?

2020-10-26 20:46 UTC, codeallthethingz commented on gapi/gapi.go
> +	json.NewDecoder(body).Decode(&data)
are you swallowing an error here?

2020-10-26 20:46 UTC, codeallthethingz commented on api/index.go
> +	salesForceDAO, err = salesforce.NewDAO(map[string]string{
why don't you just pass in the values as named values?  

`NewDAO(env.SfURL, etc...`

2020-10-26 20:46 UTC, codeallthethingz commented on api/index.go
> +			err := errors.New("missing required Salesforce credentials")
Seems like some repetition.
How about adding a function

```
sendInternalServerError(w, errors.New("missing required Salesforce credentials"))
```

2020-10-26 20:46 UTC, codeallthethingz commented on gapi/dao.go
> +func NewDAO(vars map[string]string) (DAO, error) {
If you're not passing in a map here, and have already done the ENV validation, you can remove the error return value entirely.

2020-10-26 21:13 UTC, wafer-bw commented on api/index.go
> +			err := errors.New("missing required Salesforce credentials")
Definitely. Will be added in next push

2020-10-26 21:14 UTC, wafer-bw commented on gapi/gapi.go
> +	json.NewDecoder(body).Decode(&data)
Good catch, ty.

2020-10-27 13:52 UTC, wafer-bw commented on api/index.go
> +	salesForceDAO, err = salesforce.NewDAO(map[string]string{
done

2020-10-27 13:58 UTC, wafer-bw commented on gapi/gapi.go
> +	now := time.Now().Format(time.RFC3339)
We decided to standardize on UTC

2020-10-27 14:00 UTC, wafer-bw commented on gapi/dao.go
> +	bulletPreset := "BULLET_DISC_CIRCLE_SQUARE"
They only document which string to use as far as I can tell here:
https://godoc.org/google.golang.org/api/docs/v1#CreateParagraphBulletsRequest

2020-10-27 18:11 UTC, wafer-bw commented on gapi/gapi.go
> +func jsonDecode(body io.ReadCloser) map[string]interface{} {
Switched over to google api libraries

2020-10-27 18:11 UTC, wafer-bw commented on gapi/gapi.go
> +	now := time.Now().Format(time.RFC3339)
*correction - we've made it use the invoking slack user's timezone

2020-10-27 18:39 UTC, codeallthethingz requested changes
couple of minor things, no need to review again after those changes are made.  

Overall beautiful PR.  

@grrilla

2020-10-27 18:39 UTC, codeallthethingz commented on api/index.go
> +	DevMode                     string `split_words:"true" required:"true" default:"production"`
I don't think you should have a default here.  You should have it required but fail if it isn't chosen.   That's generally the better pattern to prevent you from accidentally starting in production mode locally, or development mode in production.

2020-10-27 18:39 UTC, codeallthethingz commented on api/index.go
> +		internalServerError(w, err)
I'd change to `sendInternalServerError` as that implies it's not going to panic or do anything different.

2020-10-27 18:39 UTC, codeallthethingz commented on api/index.go
> +	sapiDAO = sapi.NewDAO(env.SlackVerificationToken, env.SlackOauthToken)
this is much more beautiful  and understandable.

2020-10-27 18:47 UTC, codeallthethingz approved these changes
🎉

2020-10-27 19:33 UTC, merged