Bit of cleaning
searchspring/nebo pull request #18
Opened 2020-10-28 23:06 UTC by codeallthethingz

… links to fire team and fire channel

2020-10-28 23:07 UTC, codeallthethingz commented on api/index.go
> -		Text:         "Fire usage:\n`/fire <fire title>` - generate a fire checklist to handle the fire",
The nature of a fire is that generally we don't know what it is at the beginning so giving it a title too early can be detrimental.

2020-10-28 23:07 UTC, codeallthethingz commented on go.mod
> -	cloud.google.com/go v0.68.0 // indirect
removed all the oauth stuff as it's no longer needed.

2020-10-28 23:08 UTC, codeallthethingz commented on vercel.json
> +    }
map to / -> /api so you don't have to know any of that in slack.

2020-10-28 23:10 UTC, codeallthethingz commented on .github/CODEOWNERS
> -* @codeallthethingz @wafer-bw
holding on to this :)

2020-10-29 13:41 UTC, wafer-bw requested changes

2020-10-29 13:41 UTC, wafer-bw commented on api/index.go
> +		"5. If a real fire - announcemer posts to the announcements channel \"There is a fire and engineering is investigating, updates will be posted in a thread on this message\"\n" +
If you can link channels like you do on ln283, can we also update ln287 to link directly to the #announcements channel?

2020-10-29 13:41 UTC, wafer-bw commented on api/index.go
> +			"2. Update the announcements channel\n" +
Same thing here, are we able to turn this into a link to the channel?

2020-10-29 13:41 UTC, wafer-bw commented on api/index.go
> +		"7. Fight! " + getMeetLink("fire-investigation") + "\n\n\n" +
I know it's rare, but we've had it happen before where both teams have separate fires going on. In order to avoid collisions we should get a meet link with an autogenerated title or add the title of the channel the fire was called like `eng-pulse-fire-investigation`

2020-10-29 13:41 UTC, wafer-bw commented on api/index.go
> +			"3. If applicable, schedule a post mortem\n",
I didn't think to add it in our PRs but now that I'm thinking about firedown a bit, we should also have a step to move the doc to the "Post Mortems" folder, I don't think we should have any stale fires within "Current Fires" folder in GDrive.

2020-10-29 13:45 UTC, codeallthethingz commented on api/index.go
> +		"5. If a real fire - announcemer posts to the announcements channel \"There is a fire and engineering is investigating, updates will be posted in a thread on this message\"\n" +
I also spelled announcer wrong.

2020-10-29 14:22 UTC, codeallthethingz commented on api/index.go
> +			"3. If applicable, schedule a post mortem\n",
not the scope of this change

2020-10-29 14:40 UTC, wafer-bw approved these changes

2020-10-29 14:41 UTC, merged