NPS Endpoint Feature
searchspring/nebo pull request #23
Opened 2021-04-13 16:30 UTC by MatthewHightech

#### This PR includes the addition of the NPS Endpoint for securely posting the NPS, and customer data to a specified slack channel. 

- The slack endpoint remains `/`
- The new NPS endpoint is at `/nps` to be formatted as shown below
`/nps?name=clientName&email=clientEmail&website=clientWebsite&rating=clientRating(0-10)`

The name, email, and website fields are mandatory but the rating field is optional and can be replaced by feedback if received by the client as shown below

- `/nps?name=clientName&email=clientEmail&website=clientWebsite&feedback=clientFeedback`

The new code written has a test coverage of 66%

A UI example of various message types can be seen below

<img width="667" alt="Screen Shot 2021-04-13 at 9 19 12 AM" src="https://user-images.githubusercontent.com/47284433/114587597-aed28300-9c3a-11eb-9a9d-175a11a62f53.png">

2021-04-13 18:21 UTC, MatthewHightech commented
Do not merge yet. Further testing with the endpoint is required.

2021-04-14 16:27 UTC, codeallthethingz requested changes
couple of changes, more to come but want to wait for the channel ID -> env change

2021-04-14 16:27 UTC, codeallthethingz commented on api/nps/index.go
> +			attachments.Color = "#35a64f"
Could extract these strings to constants and give them a good name.

2021-04-16 02:40 UTC, codeallthethingz approved these changes
Nice work.  some small syntax changes and one spidey-sense that there is a library.

2021-04-16 02:40 UTC, codeallthethingz commented on api/nps/README.md
> +## NPS Endpoint Docs 📋
This readme should be joined on to the one in the root.  Probably no one will ever see this one. :)

2021-04-16 02:40 UTC, codeallthethingz commented on api/nps/index.go
> +
remove this blank line, good to have your iferr flush against the line that made the err.

2021-04-16 02:40 UTC, codeallthethingz commented on api/nps/index.go
> +	}
Add a final `else {...` for when neither of those things are passed in that way you can see an error condition in slack and know to fix it.

2021-04-16 02:40 UTC, codeallthethingz commented on api/nps/index.go
> +	attachments.Fields = append([]slack.AttachmentField{newField}, attachments.Fields...)
```suggestion
	attachments.Fields = append(attachment.Fields, newField)
```

2021-04-16 02:40 UTC, codeallthethingz commented on api/nps/index.go
> +func parseUrl(r *http.Request) (map[string][]string, error) {
I feel like this whole funcction could be replaced with a library that turns URL params into a struct.  Just like the environment variables -> struct library.  Have a look for one.

2021-04-16 02:40 UTC, codeallthethingz commented on api/nps/index.go
> +	log.Println(err.Error())
As you are printing out the error in the sendInternalServerError and are also printing out the error in the code above where you call this function you can either remove it here, or in the calling places in your code.  Which approach will you chose and why?

2021-04-16 02:40 UTC, codeallthethingz commented on api/nps/index_test.go
> +	//"github.com/stretchr/testify/require"
remove these commented out piecces.  Generally delete the code.  Everything should be in your local version control.  If it isn't, maybe instead of commenting out code, you go commit to your branch then delete the code.

2021-04-16 02:40 UTC, codeallthethingz commented on api/nps/index_test.go
> +func TestHandlerMissingEnvVars(t *testing.T) {
Instead of a comment here, rename the function to be more descriptive

2021-04-16 02:40 UTC, codeallthethingz commented on api/slack/index.go
> +		log.Print(err.Error())
```suggestion
		log.Println(err.Error())
```

2021-04-19 16:50 UTC, MatthewHightech commented on api/nps/index.go
> +	log.Println(err.Error())
I'm going to remove the fmt.println in the main function because a function to deal with errors should have all the code that has to do with the error contained in it. Another reason to use the log instead of the fmt is because the log library uses a timestamp, and is "thread safe"

2021-04-20 17:09 UTC, merged