Check for Prospect Customer
searchspring/nebo pull request #32
Opened 2021-07-14 16:53 UTC by MatthewHightech

This PR fixes the error where the customers who are only prospects can be displayed from Metabase since there is no field that specifies prospect or not. 

The Salesforce query was adjusted to return all customers, prospect or not, and now if a match is found between the 2 databases and the Salesforce marks it as a prospect, neither the SF nor MB entry will be displayed in the slack response.

This has been tested with various examples including the one that Peter noticed to be the problem in the first place and seems to be working now.

2021-07-14 16:58 UTC, chrispellett commented on services/aggregate/aggregate.go
> +			if salesforceData[i].Type == "Prospect" {
Can you add some comments around this section? I don't understand why only "Prospect" is getting skipped in this loop. (Also, how that relates to the code that was changed in the salesforce query as it referred to customer and inactive customer)

2021-07-14 16:58 UTC, chrispellett commented on services/aggregate/aggregate.go
> +			if v.Type != "Prospect" {
Should this only be "Customer" or "Inactive Customer" (compared to what the code did before)?

2021-07-15 16:05 UTC, chrispellett approved these changes

2021-07-15 16:09 UTC, codeallthethingz commented on dals/salesforce/salesforce.go
> +		Type := fmt.Sprintf("%s", record["Type"])
if record type is already a string, we don't need to wrap it in a string conversion.

2021-07-15 16:12 UTC, codeallthethingz requested changes
nice work.  needs a bit of code cleanup.  

Also I don't see any test changse.

2021-07-15 16:12 UTC, codeallthethingz commented on services/aggregate/aggregate.go
> +	}
Extract this out to a function and then you can delete the comment if the function has a good name.

2021-07-15 16:12 UTC, codeallthethingz commented on services/aggregate/aggregate.go
>  	}
same here, could extract to well named function

2021-07-15 16:12 UTC, codeallthethingz commented on services/aggregate/aggregate.go
> +			index = i
if you just return here rather than breaking from in this loop, you can delete all those temp variables.

2021-07-16 16:03 UTC, codeallthethingz requested changes
minor function name change

2021-07-16 16:03 UTC, codeallthethingz commented on services/aggregate/aggregate.go
>  	aggregatedData = truncateAccounts(aggregatedData)
Truncate which accounts?

2021-07-16 16:41 UTC, MatthewHightech commented on services/aggregate/aggregate.go
>  	aggregatedData = truncateAccounts(aggregatedData)
It's a pretty general function that will take any array of accounts and returns the first 20 elements. It was part of the program before I started working with it so I just kept it but let me know if we still need it or not.

2021-07-16 19:51 UTC, merged