Updated Readme
searchspring/nebo pull request #34
Opened 2021-08-20 20:18 UTC by MatthewHightech

Added info on downloading env file and deploying to production.

2021-08-20 20:23 UTC, evanjohnso commented on README.md
> +<<<<<<< HEAD
think there's some leftovers here and `line 90`

2021-08-20 20:48 UTC, MatthewHightech commented on README.md
> +<<<<<<< HEAD
Ahhh thanks haha. I always miss those...

2021-08-20 20:51 UTC, evanjohnso commented on README.md
> +<<<<<<< HEAD
no matter what IDE i'm building in i always go back to VS Code for merge conflicts. idk why, i just like their little helper UI thingy-mo-bobber

2021-08-20 20:51 UTC, evanjohnso approved these changes

2021-08-20 22:04 UTC, chrispellett requested changes

2021-08-20 22:04 UTC, chrispellett commented on README.md
> +1. Download `nebo.env` from SSEng in 1password
Please add href to the item directly

2021-08-20 22:04 UTC, chrispellett commented on README.md
> +2. Create a .env file for local development
Is this needed given the step you just added?

2021-08-20 22:04 UTC, chrispellett commented on README.md
> +5. Deploy using `vercel --prod`
Should there be a step to "revert" any localhost URLs in slack?

2021-08-23 16:01 UTC, chrispellett approved these changes

2021-08-23 16:06 UTC, merged