Boost actions
searchspring/nebo pull request #35
Opened 2021-08-20 21:06 UTC by evanjohnso

* proof of concept here, 3 basic commands that simply forward responses from the Boost API into Slack
* first run at GoLang here, so be gentle (but please destroy it at the same time)

2021-08-20 21:16 UTC, neil4tell reviewed
I noticed that some function names use title case and some camel case. What's the Golang preference?

2021-08-20 21:18 UTC, evanjohnso commented
the functions/types that begin with an uppercase letter are exported

2021-08-31 20:55 UTC, evanjohnso commented
just a lil ping when you have time to review @codeallthethingz - i know you just got back from holiday Monday

2021-09-02 13:48 UTC, chrispellett requested changes
Nice go on your first go of go :)

2021-09-02 13:48 UTC, chrispellett commented on dals/boost/azureStorage.go
> +type ICloudQueue interface {
Golang convention is not prefix with "I" like in C#

2021-09-02 13:48 UTC, chrispellett commented on dals/boost/azureStorage.go
> +	envconfig.Process("", &env)
I'm not 100% sure I understand what this is doing? Is it to pull in environment variables?

2021-09-02 13:48 UTC, chrispellett commented on dals/boost/azureStorage.go
> +	ctx := context.TODO() // This example uses a never-expiring context.
You probably want to thread context through from where this is called from (just like you would a cancellationtoken in C#)

2021-09-02 13:48 UTC, chrispellett commented on dals/boost/azureStorage.go
> +	bytes, _ := json.Marshal(cloudEvent)
Best to not ignore errors

2021-09-02 13:48 UTC, chrispellett commented on dals/boost/boost.go
> +func HandleGetStatusRequest(trackingCode string, client *common.Client) map[string]interface{} {
Since you know the endpoint, perhaps better to convert to a known type structure? (probably the ones from above?)

2021-09-02 13:48 UTC, chrispellett commented on dals/boost/boost.go
> +func HelpText() string {
~~This doesn't feel like a DAL thing, but rather a handler thing (since the DAL shouldn't know anything about slack)~~
Meh, looks like other parts of nebo have similarities

2021-09-02 13:48 UTC, chrispellett commented on dals/boost/boost_test.go
> +	"github.com/stretchr/testify/assert"
Just wondering if assert is adding something that require can't provide? I _believe_ we use require in most places

2021-09-02 13:48 UTC, chrispellett commented on dals/boost/mocks/queueClient.go
> +// ::NOTE:: The ONLY reason this file is in `boost/mocks` and not `mocks` is because of a brutal
I think we may want to dig in a bit on this. Putting a file in a place named "mocks" feels like it is going to cause a lot of confusion. Could you elaborate on what the specific circular dependency is?

2021-09-02 13:48 UTC, chrispellett commented on dals/boost/mocks/queueClient.go
> +		return "Better double check that queue", nil
Not an error?

2021-09-02 13:48 UTC, chrispellett commented on dals/boost/mocks/queueClient.go
> +	return "Event type not handled, yet", nil
Not an error?

2021-09-02 13:48 UTC, chrispellett commented on handlers/slackCommands/slackCommands_test.go
> +func TestBoostCommandsThatAddToTheAzureQueue(t *testing.T) {
Unit testing best practice would be to break this into individual tests. At the moment, if one of the earlier checks fails (for a "different test case") then any other failures are hidden away.

For the repetitive cases, I find using t.Run() to help keep things consolidated but by gaining the granularity of the cases

2021-09-02 14:38 UTC, evanjohnso commented on dals/boost/azureStorage.go
> +	bytes, _ := json.Marshal(cloudEvent)
most methods seem to return `(someType, error)` is there a cleaner way to handle errors without every other line in your code being if `err != nil`

2021-09-02 14:39 UTC, evanjohnso commented on dals/boost/azureStorage.go
> +	envconfig.Process("", &env)
yup, that's it. just wraps it up

2021-09-02 14:40 UTC, evanjohnso commented on dals/boost/boost_test.go
> +	"github.com/stretchr/testify/assert"
oh, probably not. i'll switch that up

2021-09-02 14:46 UTC, evanjohnso commented on dals/boost/mocks/queueClient.go
> +		return "Better double check that queue", nil
when i work locally i test on a different queue than `dispatch-main` 

this was just a way to make the tests fail if i forgot to change it back

2021-09-02 14:50 UTC, evanjohnso commented on handlers/slackCommands/slackCommands_test.go
> +func TestBoostCommandsThatAddToTheAzureQueue(t *testing.T) {
yeah i usually try to keep them small, but this one was the closest i could get to an integration test, which we'e been trying to mock out user flow.

i was on the fence about the style at first, but it's kind of nice if you're new to the codebase to find a big ole test that kind of gently walks you through what a user might do

2021-09-02 15:58 UTC, evanjohnso commented on dals/boost/boost.go
> +func HandleGetStatusRequest(trackingCode string, client *common.Client) map[string]interface{} {
goal here was a flexible method to take any *flat* json and format it for a slack response. this was what i came up with since there's no generics .. didn't want to add a new type for every endpoint, because i don't really care about it or its fields, i'm just gonna forward them straight to slack.
 
 see `TestFormatMapResponse`
 
 is there a better way to accomplish this? or is bloating with extra types && the duplicating `writeJsonToSlackMethod` method for each type the no-generics-Go way

2021-09-02 16:15 UTC, chrispellett commented on dals/boost/mocks/queueClient.go
> +		return "Better double check that queue", nil
If the goal is for something to fail, then that feels like it should still be an error. That is one of the goals of that type. Generally there is little-to-no value in having magic strings like this to represent an issue

2021-09-02 16:17 UTC, chrispellett commented on dals/boost/mocks/queueClient.go
> +// ::NOTE:: The ONLY reason this file is in `boost/mocks` and not `mocks` is because of a brutal
That doesn't _sound_ like a circular reference (if I am reading it right). Circular I think would be more like slackMessage_test references CloudEvent which references a mock which reference slackMessage_test (or whathaveyou).

Might be worth posting a screenshot of the error if you are able to reproduce

2021-09-02 16:19 UTC, chrispellett commented on dals/boost/boost.go
> +func HandleGetStatusRequest(trackingCode string, client *common.Client) map[string]interface{} {
This is probably a stylistic thing. If the intent is to not care about the types then the map approach would work.

That being said, Golang seems to embrace the write-the-noise aspect of programming, so adding extra type definitions wouldn't be "anti-Go".

It is just nebo, so not a big deal either way

2021-09-02 16:21 UTC, chrispellett commented on dals/boost/azureStorage.go
> +	bytes, _ := json.Marshal(cloudEvent)
Not really. This is a go-ism. Not too different from other languages having if x != null, etc.

Personally, I don't mind the error as a type (compared to null/nil checks), but I hate that the language doesn't have something more advanced to reduce the noise of the if err != nil. Something like computation expressions (monads) in F# would be super valuable to just let error "fall out" automagically. But alas, Google does not decree it so

2021-09-02 16:23 UTC, chrispellett commented on dals/boost/azureStorage.go
> +	envconfig.Process("", &env)
Okay. In that case, generally you want to put that closer to the entrypoint of the application. A DAO shouldn't know _where_ it's config comes from, only that it should have a dependency on some sort of config (whether object or a couple fields, etc.). Coming from environment, json file, web service, etc. usually belongs in the startup/setup aspect

2021-09-02 21:06 UTC, chrispellett approved these changes

2021-09-02 21:32 UTC, merged