Add family command
searchspring/nebo pull request #41
Opened 2021-09-09 13:06 UTC by scottypickering

![Screen Shot 2021-09-09 at 8 05 52 AM](https://user-images.githubusercontent.com/18061415/132691222-406bc61d-1474-47b8-90a2-d1a38fe2292c.png)

2021-09-09 13:39 UTC, chrispellett requested changes

2021-09-09 13:39 UTC, chrispellett commented on common/common.go
> +		initialText = "Accounts for family: " + accountInfos[0].ParentDomain
The next block does a check on len(accountInfo) == 0. Does that not mean that this could have no results? If so, you will get an error here trying to access an element that does not exist

2021-09-09 13:39 UTC, chrispellett commented on dals/metabase/metabase.go
> +		log.Fatal(err)
Are you sure you want Fatal?

https://pkg.go.dev/log#Fatal

> Fatal is equivalent to Print() followed by a call to os.Exit(1).

2021-09-09 13:39 UTC, chrispellett commented on dals/salesforce/salesforce_test.go
> +	msg := common.FormatAccountInfos(response, "fabletics", false)
Is there a test where family = true? I took a look and don't see one...

2021-09-09 13:39 UTC, chrispellett commented on services/aggregate/aggregate.go
> +		return nil, nil
Shouldn't this return the err?

2021-09-09 13:39 UTC, chrispellett commented on services/aggregate/aggregate.go
> +		return nil, nil
Shouldn't this return the err?

2021-09-09 13:39 UTC, chrispellett commented on services/aggregate/aggregate.go
> +func (d *AggregateServiceImpl) QueryFamily(search string) ([]byte, error) {
This function looks identical to Query with only the metabase QueryFamily and the FormatAccountInfos(...true) param. If so, it feels like this behaviour should be combined so as to not be repeated.

For example, could we just have one Query() call with the family parameter passed in? (not the only option)

2021-09-09 16:08 UTC, chrispellett requested changes

2021-09-09 16:08 UTC, chrispellett commented on services/aggregate/aggregate.go
> +	msg := common.FormatAccountInfos(aggregatedData, search, false)
Should this not be set to the family flag value?

2021-09-09 16:08 UTC, chrispellett commented on dals/salesforce/salesforce_test.go
> +
I can't seem to find a test with family=true and there being >=1 result (i.e. a test that actually invokes most of the logic, the above test wouldn't check much)

2021-09-09 18:06 UTC, scottypickering commented on services/aggregate/aggregate.go
> +	msg := common.FormatAccountInfos(aggregatedData, search, false)
I'm not really sure what this means. Some kind of enum in Go?

2021-09-09 18:26 UTC, chrispellett commented on services/aggregate/aggregate.go
> +	msg := common.FormatAccountInfos(aggregatedData, search, false)
You have a parameter for family you pass in to this function. But then this line you just hardcode false. Shouldn't that be the argument that is passed in?

2021-09-09 18:30 UTC, scottypickering commented on services/aggregate/aggregate.go
> +	msg := common.FormatAccountInfos(aggregatedData, search, false)
Right, "family" is a boolean that is true if the goal is to format the account info as a family. That's not what we're trying to do in this function, so we pass false instead.

2021-09-09 20:07 UTC, chrispellett commented on services/aggregate/aggregate.go
> +	msg := common.FormatAccountInfos(aggregatedData, search, false)
Okay, I'm really confused then.

That new parameter in FormatAccountInfos function is called "family". _This_ function has a parameter called "family". If you don't intend to pass the argument of _this_ function (for family) to FormatAccountInfos, do those two arguments have different meanings? Are they _different_ families in some way?

2021-09-09 20:09 UTC, chrispellett commented on services/aggregate/aggregate.go
> +	msg := common.FormatAccountInfos(aggregatedData, search, false)
Is there a place that you actually call FormatAccountInfos and pass true for the family argument?

2021-09-09 20:11 UTC, scottypickering commented on services/aggregate/aggregate.go
> +	msg := common.FormatAccountInfos(aggregatedData, search, false)
Nope, you're right. I was confused after combining the two into one aggregate function. Fixed.

2021-09-10 17:44 UTC, chrispellett requested changes

2021-09-10 17:44 UTC, chrispellett commented on dals/salesforce/salesforce_test.go
> +	msg := common.FormatAccountInfos(response, "fabletics", true)
This looks to be invoking the new code, but I', not really clear how it is testing the _family_ aspect of the code. I appreciate the code is very similar to the "non family"/existing behaviour, but this test should be highlighting/focusing on the special behaviour of family.

2021-09-13 13:51 UTC, chrispellett approved these changes

2021-09-13 13:52 UTC, merged