Add fallback query for staging sites
searchspring/nebo pull request #42
Opened 2021-09-14 20:13 UTC by scottypickering

Fixes this issue: https://searchspring.slack.com/archives/CSKTXQ61W/p1631540664116400

2021-09-14 20:48 UTC, chrispellett commented on dals/metabase/metabase.go
> +		q = "SELECT " + accountFields + " " +
Are we able to combine this with the above sql statement to eliminate the duplication? They look to be the same except for the presales/sandbox flags? Perhaps pull into a function?

2021-09-15 17:44 UTC, codeallthethingz requested changes
some refactoring away comments

2021-09-15 17:44 UTC, codeallthethingz commented on dals/metabase/metabase.go
> +	if len(info.Data.Rows) == 0 {
Generally a comment is an indicator that you should extract a function.

if noResults(info) {
   info, resp, err = retryWithoutSandbox(sanatized, etc....)
}

2021-09-20 16:09 UTC, chrispellett approved these changes

2021-09-21 14:05 UTC, merged